version: "3.3"
services:

  elasticsearch:
    image: elasticsearch:7.13.2
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    image: kibana:7.13.2
    ports:
      - "5601:5601"
    links:
      - elasticsearch
