openapi: 3.0.3
info:
  title: Rating
  description: 'A training project to create a rating. A service that will help to add a rating to any entity'
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: http://localhost:8080/v1
tags:
  - name: rating
    description: Rating
paths:
  /rating/create:
    post:
      tags:
        - rating
      summary: Create rating.
      operationId: createRating
      requestBody:
        description: Model to create the rating.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RatingCreateRequest'
        required: true
      responses:
        200:
          description: Rating was successfully created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RatingResponse'
  /rating/get:
    post:
      tags:
        - rating
      summary: Get the rating by ID.
      operationId: getRating
      requestBody:
        description: String ID of the rating to get.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RatingRequest'
        required: true
      responses:
        200:
          description: Rating was successfully received.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RatingResponse'
  /rating/update:
    post:
      tags:
        - rating
      summary: Update the rating by vote.
      operationId: updateRating
      requestBody:
        description: Vote to update the rating.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VoteRequest'
        required: true
      responses:
        200:
          description: Rating was successfully updated.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RatingResponse'
components:
  schemas:
    BaseRequest:
      type: object
      title: Базовая структура запроса
      properties:
        type:
          type: string
          title: Тип запроса
          description: 'Идентификатор типа запроса. Используется в качестве дискриминатора при десериализации.
            Наиболее востребован при пересылке через Websocket и другие транспорты без явного выделения канала.'
      discriminator:
        propertyName: type
    RatingRequest:
      allOf:
        - $ref: '#/components/schemas/BaseRequest'
        - type: object
          properties:
            id:
              type: string
              description: Rating ID.
    RatingCreateRequest:
      allOf:
        - $ref: '#/components/schemas/BaseRequest'
        - type: object
          properties:
            groupId:
              type: string
              description: Rating group ID.
    VoteRequest:
      allOf:
        - $ref: '#/components/schemas/BaseRequest'
        - type: object
          properties:
            id:
              type: string
              description: Vote ID.
            ratingId:
              type: string
              description: Rating ID.
            value:
              type: integer
              format: integer32
              description: Rating value.
            voterId:
              type: string
              description: Voter ID.
    VoteResponse:
      type: object
      properties:
        id:
          type: string
          description: Vote ID.
        ratingId:
          type: string
          description: Rating ID.
        value:
          type: integer
          format: integer32
          description: Rating value.
        voterId:
          type: string
          description: Voter ID.
        voteDateTime:
          type: string
          description: Vote date and time.
    RatingResponse:
      type: object
      properties:
        id:
          type: string
          description: Rating ID.
        groupId:
          type: string
          description: Rating group ID.
        value:
          type: number
          format: double
          description: Rating value.
        votes:
          type: array
          items:
            $ref: '#/components/schemas/VoteResponse'
          description: Rating's votes.
